name: sdadadatdlam
services:

    front:
        build: ./sdadadatdlam-frontend
        container_name: front
        ports: 
            - 80:80
        networks:
            - backshots
            - frontman
        depends_on:
            python:
                condition: service_started
    python:
        build: ./backend
        container_name: backend
        ports: 
            - "80:80"
        networks:
            - backshots
        depends_on:
            postgres:
                condition: service_healthy
                restart: true
            redis:
                condition: service_started
    postgres:
        image: postgres:alpine
        container_name: prosgres
        restart: always
        volumes:
            - db-data:/var/lib/postgresql
        ports: 
            - 5432:5432
        networks:
            - backshots
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: passowrd
            POSTGRES_DB: sdadadatdlam
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
            interval: 10s
            retries: 5
            start_period: 30s
            timeout: 10s
    redis:
        image: redis:alpine
        container_name: my_body_is_redis
        restart: always
        command: redis-server --save 20 1 --loglevel warning --requirepass sdadadatdlam
        volumes:
            - redis-data:/data
        ports:
            - 6379:6379
        networks:
            - backshots
    tailscale:
        image: tailscale/tailscale:stable
        networks:
            - frontman
    selenium-standalone:
        image: selenium/standalone-docker:4.40
        container_name: selenium-docker
        restart: always
        volumes:
            - ./backend/config.toml:/opt/selenium/config.toml
            - /var/run/docker.sock:/var/run/docker.sock
            - selenium-temp:/home/seluser/Downloads
            - selenium-temp:/opt/selenium/assets
        environment:
            - CONFIG_FILE=/opt/bin/config.toml
            - SE_NODE_DOCKER_CONFIG_FILENAME=config.toml
        ports: 
            - 4444:4444
        networks:
            - backshots

volumes:
    db-data: {}
    redis-data: {}
    selenium-temp: {}
configs:
    httpd-config:
        external: true
networks:
    frontman: {}
    backshots: {} 