name: sdadadatdlam
services:
    front:
        build: ./sdadadatdlam-frontend
        container_name: sdadadatdlam-frontend
        ports: 
            - 8080:80
        networks:
            - backshots
        depends_on:
            backend:
                condition: service_started
        env_file: ".env.prod"
        expose:
            - 8080
    backend:
        build: ./backend
        container_name: sdadadatdlam-backend
        ports: 
            - "80:80"
        networks:
            - backshots
            - playwright
        depends_on:
            postgres:
                condition: service_healthy
                restart: true
            redis:
                condition: service_started
        volumes:
            - ./logs:/usr/app/src/logs
            - ./temp:/temp
            - /var/run/docker.sock:/var/run/docker.sock
        env_file: ".env.prod"
        secrets:
            - google_creds
            - google_token
    toywrong:
        build: 
            context: ./playwright
        container_name: toywrong
        networks: 
            - playwright
        depends_on: 
            selenium:
                condition: service_healthy

        ports:
            - "9222:9222"
        env_file: ".env.prod"
    postgres:
        image: postgres:alpine
        container_name: prosgres
        restart: always
        volumes:
            - db-data:/var/lib/postgresql
        ports: 
            - 5000:5432
        expose:
            - 5000
        networks:
            - backshots
        env_file: ".env.prod"
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
            interval: 10s
            retries: 5
            start_period: 30s
            timeout: 10s
    redis:
        image: redis:alpine
        container_name: my_body_is_redis
        restart: always
        command: redis-server --save 20 1 --loglevel warning
        volumes:
            - redis-data:/data
        ports:
            - 6379:6379
        networks:
            - backshots

    selenium:
        image: selenium/standalone-docker:4.40
        container_name: selenium
        restart: always
        volumes:
            - ./selenium_config.toml:/opt/selenium/config.toml
            - /var/run/docker.sock:/var/run/docker.sock
            - ./temp:/temp
            - selenium-temp:/opt/selenium/assets
        environment:
            - CONFIG_FILE=/opt/bin/config.toml
            - SE_NODE_DOCKER_CONFIG_FILENAME=config.toml
        ports: 
            - 4444:4444
        networks:
            - playwright
        healthcheck:
            test: ["CMD", "/opt/bin/check-grid.sh"]
            interval: 10s
            timeout: 5s
            retries: 3
            start_period: 10s

volumes:
    db-data: {}
    redis-data: {}
    selenium-temp: {}
    tailscale-data: {}

configs:
    httpd-config:
        external: true
networks:
    backshots: {} 
    playwright: {}          

secrets:
    google_creds:
        file: ./google-credentials-web.json
    google_token:
        file: ./token.json