FROM python:3.14.5-slim-trixie

WORKDIR /usr/app/src

COPY requirements.txt ./

RUN pip install --prefer-binary --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 80/tcp
# escape=\
CMD ["fastapi", "run", "main.py", "--port", "80", "--host", "0.0.0.0", "--forwarded-allow-ips=\"*\"", "--proxy-headers"]