FROM python:3.13.2-alpine

WORKDIR /usr/app/src

COPY requirements.txt ./

RUN apk update && apk add --no-cache \
    py3-greenlet

RUN pip install -r requirements.txt

COPY . .

CMD ["fastapi", "run", "backend/main.py", "--port", "80", "--host", "0.0.0.0"]