FROM python:3.14.5-alpine3.23

WORKDIR /usr/app/src

COPY requirements.txt ./

RUN pip install --only-binary :all: --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 80/tcp

CMD ["fastapi", "run", "main.py", "--port", "80", "--host", "0.0.0.0"]