FROM node:26-slim
 
WORKDIR /usr/app

COPY ./playwright_config.json config.json

RUN npm install playwright

# RUN npx playwright install --only-shell --with-deps chromium

CMD ["npx", "playwright", "launch-server", "--browser", "chromium", "--config", "config.json"]