FROM node:lts-alpine AS build

WORKDIR /usr/app/front

COPY package*.json .

RUN npm ci

COPY . .

RUN npm run build

FROM nginx:stable-alpine-slim

COPY --from=build /usr/app/front/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf
EXPOSE 80/tcp

CMD ["/usr/sbin/nginx", "-g", "daemon off;"]